# Generated by Django 4.0.4 on 2022-08-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('count', models.IntegerField()),
                ('slug', models.SlugField(max_length=48, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('on_sale', models.BooleanField(default=False)),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
