# Generated by Django 4.0.4 on 2022-08-30 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='count',
            new_name='stock_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.TextField(blank=True, choices=[('Suits', 'Suits'), ('Shoes', 'Shoes'), ('Blazers', 'Blazers'), ('Sweaters', 'Sweaters'), ('Accessories', 'Accessories'), ('Jewellery', 'Jewellery'), ('Perfumes', 'Perfumes'), ('Shirts', 'Shirts'), ('Trousers', 'Trousers'), ('Jackets', 'Jackets'), ('Caps', 'Caps'), ('Shorts', 'Shorts')], null=True),
        ),
        migrations.DeleteModel(
            name='ProductTag',
        ),
    ]
