# Generated by Django 4.0.4 on 2022-09-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ManyToManyField(blank=True, to='shop.product'),
        ),
    ]
