# Generated by Django 4.0.4 on 2022-09-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_productimage_product_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_title',
            field=models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], default='Mr.', max_length=3),
        ),
    ]
