# Generated by Django 4.0.4 on 2022-08-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_producttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(default='all', to='shop.producttag'),
        ),
    ]
