# Generated by Django 4.0.4 on 2022-09-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_billing_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
