# Generated by Django 4.0.4 on 2022-08-30 09:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0002_initial'),
        ('shop', '0004_orderitem_remove_cart_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_county',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_phone_no',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_postal_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_title',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_town',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_spoken_to',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_county',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_phone_no',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_postal_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_title',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_town',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='shop.product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.IntegerField(choices=[(10, 'Open'), (20, 'Submitted')], default=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customauth.customuser'),
        ),
    ]
