# Generated by Django 4.0.4 on 2022-08-30 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_order_billing_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
