# Generated by Django 4.0.4 on 2022-09-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_billing_address_order_billing_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_postal_code',
            field=models.CharField(default='00100', max_length=12),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_town',
            field=models.CharField(default='Nairobi', max_length=60),
        ),
    ]
