# Generated by Django 4.0.4 on 2022-09-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_billing_postal_code_order_billing_town'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_postal_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_title',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_town',
        ),
        migrations.AddField(
            model_name='order',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
