# Generated by Django 4.0.4 on 2022-08-30 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0002_initial'),
        ('shop', '0007_order_items_orderitem_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customauth.customuser'),
        ),
    ]
