# Generated by Django 4.0.4 on 2022-09-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_productimage_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.CharField(default='', max_length=60, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_city',
            field=models.CharField(blank=True, choices=[('MBS', 'Mombasa'), ('NBI', 'Nairobi'), ('KSM', 'Kisumu'), ('NKR', 'Nakuru')], max_length=60, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_country',
            field=models.CharField(choices=[('KE', 'Kenya')], default='KE', max_length=3, verbose_name='county'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_county',
            field=models.CharField(choices=[('001', 'Mombasa'), ('002', 'Kwale'), ('003', 'Kilifi'), ('004', 'Tana River'), ('005', 'Lamu'), ('006', 'Taita Taveta'), ('007', 'Garissa'), ('008', 'Wajir'), ('009', 'Mandera'), ('010', 'Marsabit'), ('011', 'Isiolo'), ('012', 'Meru'), ('013', 'Tharaka-Nithi'), ('014', 'Embu'), ('015', 'Kitui'), ('016', 'Machakos'), ('017', 'Makueni'), ('018', 'Nyandarua'), ('019', 'Nyeri'), ('020', 'Kirinyaga'), ('021', "Murang'a"), ('022', 'Kiambu'), ('023', 'Turkana'), ('024', 'West Pokot'), ('025', 'Samburu'), ('026', 'Trans-Nzoia'), ('027', 'Uasin Gishu'), ('028', 'Elgeyo-Marakwet'), ('029', 'Nandi'), ('030', 'Baringo'), ('031', 'Laikipia'), ('032', 'Nakuru'), ('033', 'Narok'), ('034', 'Kajiado'), ('035', 'Kericho'), ('036', 'Bomet'), ('037', 'Kakamega'), ('038', 'Vihiga'), ('039', 'Bungoma'), ('040', 'Busia'), ('041', 'Siaya'), ('042', 'Kisumu'), ('043', 'Homa Bay'), ('044', 'Migori'), ('045', 'Kisii'), ('046', 'Nyamira'), ('047', 'Nairobi')], default='Nairobi', max_length=10, verbose_name='county'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_name',
            field=models.CharField(default='', max_length=60, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_phone_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_postal_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Postal Code'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_title',
            field=models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], default='Mr.', max_length=5),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_town',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='town'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(default='', max_length=60, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(blank=True, choices=[('MBS', 'Mombasa'), ('NBI', 'Nairobi'), ('KSM', 'Kisumu'), ('NKR', 'Nakuru')], max_length=60, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_country',
            field=models.CharField(choices=[('KE', 'Kenya')], default='KE', max_length=3, verbose_name='county'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_county',
            field=models.CharField(choices=[('001', 'Mombasa'), ('002', 'Kwale'), ('003', 'Kilifi'), ('004', 'Tana River'), ('005', 'Lamu'), ('006', 'Taita Taveta'), ('007', 'Garissa'), ('008', 'Wajir'), ('009', 'Mandera'), ('010', 'Marsabit'), ('011', 'Isiolo'), ('012', 'Meru'), ('013', 'Tharaka-Nithi'), ('014', 'Embu'), ('015', 'Kitui'), ('016', 'Machakos'), ('017', 'Makueni'), ('018', 'Nyandarua'), ('019', 'Nyeri'), ('020', 'Kirinyaga'), ('021', "Murang'a"), ('022', 'Kiambu'), ('023', 'Turkana'), ('024', 'West Pokot'), ('025', 'Samburu'), ('026', 'Trans-Nzoia'), ('027', 'Uasin Gishu'), ('028', 'Elgeyo-Marakwet'), ('029', 'Nandi'), ('030', 'Baringo'), ('031', 'Laikipia'), ('032', 'Nakuru'), ('033', 'Narok'), ('034', 'Kajiado'), ('035', 'Kericho'), ('036', 'Bomet'), ('037', 'Kakamega'), ('038', 'Vihiga'), ('039', 'Bungoma'), ('040', 'Busia'), ('041', 'Siaya'), ('042', 'Kisumu'), ('043', 'Homa Bay'), ('044', 'Migori'), ('045', 'Kisii'), ('046', 'Nyamira'), ('047', 'Nairobi')], default='Nairobi', max_length=10, verbose_name='county'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_name',
            field=models.CharField(default='', max_length=60, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_phone_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_postal_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Postal Code'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_title',
            field=models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], default='Mr.', max_length=5),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_town',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='town'),
        ),
    ]
